<dialog x-ref="galleryDialog" @close="dialogClosed()" @click="if ($event.target === $el) $el.close()" aria-label="نمایش تصاویر" class="fixed inset-0 m-auto max-h-[95dvh] w-[min(1100px,96vw)] rounded-2xl bg-ink p-4 text-white backdrop:bg-black/80 sm:p-6">
    <div class="mb-4 flex items-center justify-between"><p class="text-sm" x-text="activePhotos[photoIndex]?.caption || 'عکس‌های کسب‌وکار'"></p><button type="button" @click="$refs.galleryDialog.close()" class="rounded-lg p-3 hover:bg-white/10" aria-label="بستن تصاویر"><x-icon name="close"/></button></div>
    <div class="relative flex min-h-64 items-center justify-center"><img :src="activePhotos[photoIndex]?.src" :alt="activePhotos[photoIndex]?.caption || 'تصویر کسب‌وکار'" class="max-h-[65dvh] max-w-full rounded-xl object-contain"><button type="button" @click="movePhoto(-1)" class="absolute right-0 rounded-full bg-black/60 p-3" aria-label="عکس قبلی"><x-icon name="chevron-right"/></button><button type="button" @click="movePhoto(1)" class="absolute left-0 rounded-full bg-black/60 p-3" aria-label="عکس بعدی"><x-icon name="chevron-left"/></button></div>
    <div class="mt-4 flex items-center justify-center gap-2 overflow-x-auto"><template x-for="(photo, index) in activePhotos" :key="index"><button type="button" @click="photoIndex = index" :aria-label="'عکس ' + fa(index + 1)" :aria-pressed="photoIndex === index" :class="photoIndex === index ? 'border-white' : 'border-transparent opacity-50'" class="shrink-0 overflow-hidden rounded-lg border-2"><img :src="photo.src" alt="" class="h-12 w-16 object-cover"></button></template></div><p class="mt-3 text-center text-xs text-white/70" x-text="fa(photoIndex + 1) + ' از ' + fa(activePhotos.length)"></p>
</dialog>
<dialog x-ref="reviewDialog" @close="dialogClosed()" aria-labelledby="review-dialog-title" class="fixed inset-0 m-auto max-h-[90dvh] w-[min(620px,94vw)] overflow-y-auto rounded-2xl bg-surface p-6 text-ink backdrop:bg-black/50 sm:p-8">
    <div class="flex items-center justify-between"><h2 id="review-dialog-title" class="text-xl font-bold" x-text="editingId ? 'ویرایش تجربه شما' : 'تجربه شما چطور بود؟'"></h2><button type="button" @click="$refs.reviewDialog.close()" class="rounded-lg p-3 text-muted" aria-label="بستن فرم نظر"><x-icon name="close"/></button></div>
    <p class="mt-2 text-sm text-secondary">{{ $business['name'] }} · {{ $business['neighborhood'] }}</p>
    <form @submit.prevent="submitReview()" class="mt-6 space-y-5">
        <fieldset><legend class="mb-3 text-sm font-semibold">امتیاز شما</legend><div class="flex gap-2">@for ($star = 1; $star <= 5; $star++)<label class="cursor-pointer"><input type="radio" name="rating" value="{{ $star }}" x-model.number="draft.rating" required class="peer sr-only"><span :class="draft.rating >= {{ $star }} ? 'bg-pomegranate text-white' : 'bg-soft text-muted'" class="flex size-11 items-center justify-center rounded-lg peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-pomegranate"><x-icon name="star" :filled="true" class="size-7"/></span><span class="sr-only">{{ $star }} ستاره</span></label>@endfor</div></fieldset>
        <label class="block text-sm font-semibold">خلاصه تجربه<input x-model="draft.title" maxlength="100" required placeholder="مثلاً: یک جای خوب برای عصرهای آرام" class="mt-2 min-h-12 w-full rounded-xl border border-border px-3 text-sm outline-pomegranate"></label>
        <label class="block text-sm font-semibold">نظر شما<textarea x-model="draft.body" rows="5" minlength="20" maxlength="2000" required placeholder="درباره کیفیت، فضا، برخورد و تجربه‌تان بنویسید…" class="mt-2 w-full rounded-xl border border-border p-3 text-sm leading-7 outline-pomegranate"></textarea><span class="mt-1 block text-left text-xs font-normal text-muted" x-text="fa(draft.body.length) + ' / ۲۰۰۰'"></span></label>
        <label class="block text-sm font-semibold">نوع بازدید<select x-model="draft.visit" class="mt-2 min-h-12 w-full rounded-xl border border-border px-3 text-sm"><option>با دوستان</option><option>دونفره</option><option>با خانواده</option><option>تنهایی</option></select></label>
        <div><label class="flex min-h-14 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-border text-sm text-secondary"><x-icon name="camera"/> افزودن عکس <input type="file" :disabled="uploading" accept="image/jpeg,image/png,image/webp" multiple @change="addPhotos($event)" class="sr-only"></label><p class="mt-2 text-[11px] text-muted">حداکثر ۳ عکس، هر عکس تا ۵ مگابایت</p><div class="mt-3 flex gap-2"><template x-for="(photo, index) in draft.photos" :key="index"><div class="relative"><img :src="photo.src" alt="عکس انتخاب‌شده" class="size-20 rounded-lg object-cover"><button type="button" @click="draft.photos.splice(index, 1)" class="absolute top-0 left-0 rounded-full bg-ink p-1 text-white" aria-label="حذف عکس"><x-icon name="close" class="size-4"/></button></div></template></div></div>
        <p x-show="formError" x-text="formError" role="alert" class="text-sm text-pomegranate"></p><p class="rounded-xl bg-soft p-3 text-xs leading-6 text-muted">این نسخه نمایشی است. نظر و عکس‌های شما فقط در همین مرورگر ذخیره می‌شوند و برای کسب‌وکار ارسال نمی‌شوند.</p>
        <button type="submit" :disabled="uploading" class="min-h-12 w-full rounded-xl bg-pomegranate text-sm font-bold text-white hover:bg-pomegranate-dark disabled:opacity-50" x-text="uploading ? 'در حال آماده‌سازی عکس…' : (editingId ? 'ذخیره تغییرات' : 'ثبت نظر نمایشی')"></button>
    </form>
</dialog>
<dialog x-ref="actionDialog" @close="dialogClosed()" aria-labelledby="action-title" class="fixed inset-0 m-auto w-[min(440px,94vw)] rounded-2xl bg-surface p-6 text-ink backdrop:bg-black/50">
    <div class="flex items-center justify-between"><h2 id="action-title" class="text-lg font-bold" x-text="action === 'delete' ? 'حذف نظر شما؟' : 'گزارش این نظر'"></h2><button type="button" @click="$refs.actionDialog.close()" class="p-3" aria-label="بستن"><x-icon name="close"/></button></div>
    <p class="mt-3 text-sm leading-7 text-secondary" x-text="action === 'delete' ? 'این نظر و پاسخ‌های آن از نسخه نمایشی شما حذف می‌شود.' : 'دلیل گزارش را انتخاب کنید. گزارش در این نسخه فقط به‌صورت نمایشی ثبت می‌شود.'"></p>
    <select x-show="action === 'report'" x-model="reportReason" aria-label="دلیل گزارش" class="mt-4 min-h-12 w-full rounded-xl border border-border px-3 text-sm"><option>محتوای نامناسب</option><option>تبلیغات یا هرزنامه</option><option>اطلاعات شخصی</option><option>تجربه غیرمرتبط</option></select>
    <div class="mt-6 flex gap-3"><button type="button" @click="confirmAction()" class="min-h-11 flex-1 rounded-xl bg-pomegranate text-sm font-bold text-white" x-text="action === 'delete' ? 'حذف نظر' : 'ثبت گزارش نمایشی'"></button><button type="button" @click="$refs.actionDialog.close()" class="min-h-11 rounded-xl border border-border px-5 text-sm">انصراف</button></div>
</dialog>
