@extends($admin ? 'layouts.admin' : 'layouts.community')
@section('title', 'مدیریت '.$business->name)
@section('breadcrumbs')<x-breadcrumbs :items="[['label'=>$admin ? 'پرتال مدیریت' : 'پرتال کسب‌وکار','url'=>$admin ? route('admin.dashboard') : route('business.dashboard')],['label'=>$business->name]]" />@endsection
@section($admin ? 'admin-content' : 'content')
@php
    $phones = old('phones', $business->phones ?? ($business->phone ? [['label'=>'اصلی','value'=>$business->phone]] : []));
    $websites = old('websites', $business->websites ?? ($business->website ? [['label'=>'وب‌سایت اصلی','url'=>$business->website]] : []));
    $hours = old('weekly_hours', $business->weekly_hours ?? []);
    $featuredIds = collect(old('featured_media_ids', $business->featuredPhotos->pluck('id')->all()))->map(fn($id)=>(string)$id)->all();
    $selectedSpecificationIds = collect(old('specification_ids', $business->specifications->pluck('id')->all()))->map(fn($id)=>(string)$id)->all();
    $days = \App\Services\BusinessHours::DAYS; $labels = \App\Services\BusinessHours::LABELS;
@endphp
<div id="business-manager" data-upload-url="{{ $admin ? route('admin.businesses.photos.store',$business) : route('business.businesses.photos.store',$business) }}" data-photo-base="{{ $admin ? url('/admin/businesses/'.$business->id.'/photos') : url('/business/businesses/'.$business->id.'/photos') }}" data-delete-base="{{ $admin ? url('/admin/businesses/'.$business->id.'/photos') : url('/business/businesses/'.$business->id.'/photos') }}">
<div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-pomegranate">{{ $admin ? 'پرتال مدیریت' : 'پرتال کسب‌وکار' }}</p><h1 class="mt-2 text-3xl font-extrabold">مدیریت {{ $business->name }}</h1><p class="mt-2 text-secondary">تغییرات پس از ذخیره مستقیماً در صفحه عمومی نمایش داده می‌شوند.</p></div><a class="button-secondary" href="{{ route('businesses.show',$business->slug) }}">مشاهده صفحه عمومی</a></div>
<form method="post" action="{{ $admin ? route('admin.businesses.update',$business) : route('business.businesses.update',$business) }}" class="mt-7 space-y-6">@csrf @method('put')
<section class="panel"><h2 class="text-xl font-bold">اطلاعات اصلی</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><label>نام<input class="field" name="name" required maxlength="180" value="{{ old('name',$business->name) }}"></label><label>دسته‌بندی<select class="field" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$business->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></label><x-city-select :cities="$cities" :value="old('city',$business->city)" id="management-city" name="city" label="شهر" required /><label>آدرس<input class="field" name="address" required maxlength="500" value="{{ old('address',$business->address) }}"></label><label class="sm:col-span-2">معرفی<textarea class="field" name="description" maxlength="3000" rows="5">{{ old('description',$business->description) }}</textarea></label><fieldset class="sm:col-span-2">
    <legend class="font-semibold">بازه قیمت</legend>
    <p class="mt-2 text-sm text-muted">هزینه نسبی در مقایسه با مکان‌های مشابه؛ مبلغ یا واحد پول نیست.</p>
    <div class="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">
        <label class="price-option"><input type="radio" name="price_range" value="" @checked(old('price_range', $business->price_range) === null || old('price_range', $business->price_range) === '')><span>نامشخص</span></label>
        @foreach(\App\Models\Business::PRICE_RANGES as $value => $label)
            <label class="price-option"><input type="radio" name="price_range" value="{{ $value }}" @checked((string) old('price_range', $business->price_range) === (string) $value)><span><bdi dir="ltr" class="block font-bold tracking-wider">{{ str_repeat('$', $value) }}</bdi><span class="mt-1 block text-xs">{{ $label }}</span></span></label>
        @endforeach
    </div>
    @error('price_range')<p class="field-error">{{ $message }}</p>@enderror
</fieldset></div></section>
<section class="panel">
    <h2 class="text-xl font-bold">امکانات و ویژگی‌ها</h2>
    <input type="hidden" name="specifications_present" value="1">
    <p class="mt-2 text-sm text-muted">فقط ویژگی‌هایی را انتخاب کنید که این کسب‌وکار واقعاً ارائه می‌کند.</p>
    <div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
        @foreach($specifications as $specification)
            <label class="specification-option">
                <input type="checkbox" name="specification_ids[]" value="{{ $specification->id }}" class="sr-only" @checked(in_array((string) $specification->id, $selectedSpecificationIds, true))>
                <span class="specification-option-icon"><x-icon :name="$specification->icon" /></span>
                <span class="text-sm font-bold leading-6">{{ $specification->label }}</span>
            </label>
        @endforeach
    </div>
    @error('specification_ids')<p class="field-error">{{ $message }}</p>@enderror
    @error('specification_ids.*')<p class="field-error">{{ $message }}</p>@enderror
</section>
<x-location-picker :cities="$cities" :latitude="old('latitude', $business->latitude)" :longitude="old('longitude', $business->longitude)" />
<section class="panel"><div class="flex items-center justify-between gap-3"><div><h2 class="text-xl font-bold">راه‌های تماس</h2><p class="mt-1 text-sm text-muted">برای هر مورد یک عنوان روشن وارد کنید.</p></div></div><h3 class="mt-5 font-bold">شماره‌ها</h3><div data-repeat-list="phones" class="mt-3 space-y-3">@foreach($phones as $i=>$phone)<div data-repeat-row class="grid gap-2 sm:grid-cols-[10rem_1fr_auto]"><input class="field !mt-0" name="phones[{{ $i }}][label]" maxlength="40" placeholder="عنوان" value="{{ $phone['label'] ?? '' }}"><input class="field !mt-0" name="phones[{{ $i }}][value]" maxlength="40" dir="ltr" placeholder="شماره" value="{{ $phone['value'] ?? '' }}"><button type="button" data-remove-row class="button-secondary">حذف</button></div>@endforeach</div><button type="button" data-add-row="phones" class="button-secondary mt-3">+ افزودن شماره</button><h3 class="mt-6 font-bold">وب‌سایت‌ها</h3><div data-repeat-list="websites" class="mt-3 space-y-3">@foreach($websites as $i=>$website)<div data-repeat-row class="grid gap-2 sm:grid-cols-[10rem_1fr_auto]"><input class="field !mt-0" name="websites[{{ $i }}][label]" maxlength="40" placeholder="عنوان" value="{{ $website['label'] ?? '' }}"><input class="field !mt-0" name="websites[{{ $i }}][url]" maxlength="500" dir="ltr" placeholder="https://" value="{{ $website['url'] ?? '' }}"><button type="button" data-remove-row class="button-secondary">حذف</button></div>@endforeach</div><button type="button" data-add-row="websites" class="button-secondary mt-3">+ افزودن وب‌سایت</button></section>
<section class="panel"><h2 class="text-xl font-bold">ساعت کاری هفتگی</h2><p class="mt-2 text-sm text-muted">زمان‌ها به وقت تهران هستند؛ هر روز می‌تواند حداکثر چهار نوبت داشته باشد.</p>@if(!$business->weekly_hours && $business->opening_hours)<p class="mt-4 rounded-xl bg-soft p-4 text-sm"><b>ساعت قدیمی:</b> {{ $business->opening_hours }}<br>با ذخیره یک برنامه ساختاریافته، این متن جایگزین می‌شود.</p>@endif<div class="mt-5 divide-y divide-border rounded-xl border border-border">@foreach($days as $day)<div class="grid gap-4 p-4 md:grid-cols-[7rem_7rem_1fr]" data-day="{{ $day }}"><strong class="pt-3">{{ $labels[$day] }}</strong><label class="flex min-h-12 items-center gap-2"><input type="hidden" name="weekly_hours[{{ $day }}][closed]" value="0"><input data-closed type="checkbox" name="weekly_hours[{{ $day }}][closed]" value="1" class="size-5" @checked(($hours[$day]['closed'] ?? true))> تعطیل</label><div><div data-shifts class="space-y-3">@foreach(($hours[$day]['shifts'] ?? []) as $j=>$shift)<div data-shift class="flex flex-wrap items-end gap-2"><label>از<input type="time" class="field !mt-1" name="weekly_hours[{{ $day }}][shifts][{{ $j }}][opens]" value="{{ $shift['opens'] }}"></label><label>تا<input type="time" class="field !mt-1" name="weekly_hours[{{ $day }}][shifts][{{ $j }}][closes]" value="{{ $shift['closes'] }}"></label><label class="mb-3 flex gap-2"><input type="hidden" name="weekly_hours[{{ $day }}][shifts][{{ $j }}][next_day]" value="0"><input type="checkbox" name="weekly_hours[{{ $day }}][shifts][{{ $j }}][next_day]" value="1" @checked($shift['next_day'] ?? false)> روز بعد</label><button type="button" data-remove-shift class="button-secondary">حذف</button></div>@endforeach</div><button type="button" data-add-shift class="mt-3 text-sm font-bold text-pomegranate">+ افزودن نوبت</button></div></div>@endforeach</div></section>
<section class="panel"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold">تصاویر و نمای اصلی</h2><p class="mt-1 text-sm text-muted">حداکثر پنج تصویر انتخاب کنید؛ اولین تصویر در کارت‌های فهرست استفاده می‌شود.</p></div><div class="flex flex-wrap items-end gap-2"><label class="text-sm font-semibold">نوع تصویر<select id="management-photo-category" class="field !mt-1 min-w-40">@foreach(\App\Enums\MediaCategory::cases() as $mediaCategory)<option value="{{ $mediaCategory->value }}">{{ $mediaCategory->label() }}</option>@endforeach</select></label><label class="button-secondary cursor-pointer">بارگذاری تصویر<input id="management-photo" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only"></label></div></div><p id="management-photo-status" class="mt-3 text-sm" role="status"></p><div id="featured-order" class="mt-5 flex flex-wrap gap-3">@foreach($featuredIds as $id)@php($photo=$business->photos->firstWhere('id',$id))@if($photo)<div data-featured-id="{{ $id }}" class="w-32 rounded-xl border-2 border-pomegranate p-2"><img class="h-20 w-full rounded-lg object-cover" src="{{ route('media.show',[$photo,'thumbnail'=>1]) }}" alt=""><input type="hidden" name="featured_media_ids[]" value="{{ $id }}"><div class="mt-2 flex justify-between"><button type="button" data-move="-1" aria-label="عقب">→</button><button type="button" data-unfeature>حذف</button><button type="button" data-move="1" aria-label="جلو">←</button></div></div>@endif @endforeach</div><div class="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">@foreach($business->photos as $photo)<article class="rounded-xl border border-border p-2" data-gallery-id="{{ $photo->id }}"><img class="h-32 w-full rounded-lg object-cover" src="{{ route('media.show',[$photo,'thumbnail'=>1]) }}" alt="عکس {{ $business->name }}"><label class="mt-2 block text-xs font-semibold">دسته تصویر<select data-photo-category="{{ $photo->id }}" class="field !mt-1 min-h-10 px-2 py-1 text-sm"><option value="">دسته‌بندی نشده</option>@foreach(\App\Enums\MediaCategory::cases() as $mediaCategory)<option value="{{ $mediaCategory->value }}" @selected($photo->category === $mediaCategory)>{{ $mediaCategory->label() }}</option>@endforeach</select></label><button type="button" data-feature class="button-secondary mt-2 w-full">انتخاب برای نما</button>@if($photo->source === 'management')<button type="button" data-delete-photo="{{ $photo->id }}" class="mt-2 w-full text-sm text-pomegranate">حذف تصویر مدیریتی</button>@else<p class="mt-2 text-xs text-muted">عکس کاربر؛ محافظت‌شده</p>@endif</article>@endforeach</div></section>
@if($admin)
<section class="panel" aria-labelledby="homepage-feature-title">
    <div class="flex items-start gap-3"><span class="rounded-xl bg-pomegranate/10 p-3 text-pomegranate"><x-icon name="sparkles" /></span><div><h2 id="homepage-feature-title" class="text-xl font-bold">معرفی در صفحه اصلی کیوسک</h2><p class="mt-2 text-sm leading-7 text-muted">یک عکس افقی و باکیفیت انتخاب کنید. نام، شهر و خلاصهٔ معرفی کسب‌وکار روی تصویر نمایش داده می‌شود.</p></div></div>
    <label class="mt-5 flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-border bg-canvas p-4 font-semibold"><input type="hidden" name="is_featured" value="0"><input type="checkbox" name="is_featured" value="1" class="size-5 accent-pomegranate" @checked(old('is_featured', $business->is_featured))>نمایش این کسب‌وکار در صفحه اصلی</label>
    <p class="mt-2 text-sm leading-7 text-muted">با فعال‌کردن و ذخیره، این کسب‌وکار جایگزین انتخاب قبلی صفحه اصلی می‌شود.</p>
    @error('is_featured')<p class="field-error">{{ $message }}</p>@enderror
    <fieldset class="mt-5">
        <legend class="font-semibold">تصویر صفحه اصلی</legend>
        <p class="mt-2 text-sm leading-7 text-muted">این انتخاب مستقل از تصاویر نمای اصلی کسب‌وکار است. برای نمایش در صفحه اصلی، انتخاب یک عکس ضروری است.</p>
        <label class="my-3 flex min-h-11 cursor-pointer items-center gap-2 text-sm"><input type="radio" name="hero_media_id" value="" class="size-4 accent-pomegranate" @checked(! old('hero_media_id', $business->hero_media_id))>بدون تصویر</label>
        <div class="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
            @foreach($business->photos as $photo)
                <label class="cursor-pointer overflow-hidden rounded-xl border-2 border-border has-checked:border-pomegranate has-checked:bg-pomegranate/5">
                    <img class="aspect-video w-full object-cover" src="{{ route('media.show', [$photo, 'thumbnail' => 1]) }}" alt="عکس {{ $loop->iteration }} از {{ $business->name }}" loading="lazy">
                    <span class="flex min-h-12 items-center gap-2 px-3 py-2 text-sm"><input type="radio" name="hero_media_id" value="{{ $photo->id }}" class="size-4 accent-pomegranate" @checked(old('hero_media_id', $business->hero_media_id) === $photo->id)>تصویر {{ $loop->iteration }}</span>
                </label>
            @endforeach
        </div>
        @if($business->photos->isEmpty())<p class="rounded-xl border border-dashed border-border p-5 text-sm leading-7 text-muted">ابتدا از بخش «تصاویر و نمای اصلی» یک عکس بارگذاری کنید، سپس آن را برای صفحه اصلی انتخاب کنید.</p>@endif
        @error('hero_media_id')<p class="field-error">{{ $message }}</p>@enderror
    </fieldset>
</section>
@endif
<div class="sticky bottom-3 flex justify-end rounded-2xl border border-border bg-surface/95 p-3 shadow-soft backdrop-blur"><button class="button-primary">ذخیره همه تغییرات</button></div></form></div>
@endsection
