@extends('layouts.community')
@section('title', 'مشارکت‌های من')
@section('content')
@php($labels = ['draft'=>'پیش‌نویس', 'pending'=>'در انتظار تأیید مکان', 'published'=>'منتشرشده', 'approved'=>'تأییدشده', 'corrections'=>'نیازمند اصلاح', 'rejected'=>'ردشده؛ قابل اصلاح', 'hidden'=>'پنهان‌شده برای بررسی', 'incomplete'=>'اطلاعات ناقص', 'merged'=>'ادغام‌شده'])
<h1 class="mb-7 text-3xl font-bold">مشارکت‌های من</h1>
<div class="grid gap-6 lg:grid-cols-2">
<section class="panel"><h2 class="mb-4 text-xl font-bold">پیش‌نویس‌ها</h2><p class="mb-4 text-sm text-muted">پیش‌نویس‌ها هفت روز پس از آخرین ذخیره نگهداری می‌شوند.</p>@forelse($drafts as $draft)<div class="border-t border-border py-4"><p>{{ $draft->payload['name'] ?? 'مشارکت تازه' }}</p><a class="button-secondary mt-2" href="{{ route('contribute', ['draft'=>$draft->id]) }}">ادامه / اصلاح</a><button class="button-secondary mt-2" type="button" data-discard-draft="{{ $draft->id }}">حذف پیش‌نویس</button></div>@empty<p class="text-muted">پیش‌نویس ذخیره‌شده ندارید.</p>@endforelse{{ $drafts->links() }}</section>
<section class="panel"><h2 class="mb-4 text-xl font-bold">پیام‌های مدیریت</h2>@forelse($notifications as $notification)<div class="border-t border-border py-4"><p class="font-bold">{{ $labels[$notification->data['status']] ?? $notification->data['status'] }}</p><p class="mt-2 leading-7">{{ $notification->data['reason'] }}</p></div>@empty<p class="text-muted">پیام تازه‌ای ندارید.</p>@endforelse{{ $notifications->links() }}</section>
<section class="panel"><h2 class="mb-4 text-xl font-bold">مکان‌های پیشنهادی من</h2>@forelse($businesses as $business)<div class="border-t border-border py-4"><h3 class="font-bold">{{ $business->name }}</h3><p class="my-2 text-sm text-pomegranate">{{ $labels[$business->status] ?? $business->status }}</p>@if($business->moderation_reason)<p class="text-sm leading-7">{{ $business->moderation_reason }}</p>@endif @if($business->status === 'approved')<a class="button-secondary" href="{{ route('businesses.show',$business->slug) }}">مشاهده مکان</a>@endif</div>@empty<p class="text-muted">هنوز مکانی پیشنهاد نکرده‌اید.</p>@endforelse{{ $businesses->links() }}</section>
<section class="panel"><h2 class="mb-4 text-xl font-bold">تجربه‌های من</h2>@forelse($reviews as $review)<div class="border-t border-border py-4"><h3 class="font-bold">{{ $review->business->name }}</h3>@if($review->business->status === 'approved')<a class="button-secondary mt-2" href="{{ route('businesses.show', $review->business->slug) }}">مشاهده مکان</a>@endif<p class="my-2 text-sm text-pomegranate">{{ $review->trashed() ? 'حذف‌شده' : ($labels[$review->status] ?? $review->status) }} · {{ $review->rating }} ★</p><p class="mb-3 whitespace-pre-wrap leading-7">{{ $review->body }}</p><div class="mb-4 flex flex-wrap gap-3">@foreach($review->photos as $photo)<div><img class="size-20 rounded-lg object-cover" src="{{ route('media.show', [$photo, 'thumbnail'=>1]) }}" alt="عکس تجربه من"><form method="post" action="{{ route('media.destroy', $photo) }}">@csrf @method('delete')<button class="button-secondary mt-1">حذف عکس</button></form></div>@endforeach</div><a class="button-secondary" href="{{ route('reviews.edit',$review->id) }}">ویرایش تجربه من</a>@unless($review->trashed())<form class="inline" method="post" action="{{ route('reviews.destroy',$review) }}">@csrf @method('delete')<button class="button-secondary">حذف تجربه</button></form>@endunless</div>@empty<p class="text-muted">هنوز تجربه‌ای ثبت نکرده‌اید.</p>@endforelse{{ $reviews->links() }}</section>
<section class="panel lg:col-span-2"><h2 class="mb-4 text-xl font-bold">مکان‌های ذخیره‌شده</h2>@forelse($saved as $business)<a class="button-secondary m-1" href="{{ route('businesses.show',$business->slug) }}">{{ $business->name }} · {{ $business->city }}</a>@empty<p class="text-muted">هنوز مکانی ذخیره نکرده‌اید.</p>@endforelse{{ $saved->links() }}</section>
</div>
@endsection
