@extends('layouts.community')
@section('breadcrumbs')
    <x-breadcrumbs :items="[['label' => 'حساب کاربری', 'url' => route('account')], ['label' => 'مشارکت‌های من']]" />
@endsection
@section('title', 'مشارکت‌های من')
@section('content')
@php
    $labels = ['draft' => 'پیش‌نویس', 'pending' => 'در انتظار تأیید مکان', 'published' => 'منتشرشده', 'approved' => 'تأییدشده', 'corrections' => 'نیازمند اصلاح', 'rejected' => 'ردشده؛ قابل اصلاح', 'hidden' => 'پنهان‌شده برای بررسی', 'incomplete' => 'اطلاعات ناقص', 'merged' => 'ادغام‌شده'];
    $attentionCount = $drafts->total() + $notifications->total();
@endphp

<div class="overflow-hidden rounded-3xl bg-ink text-white shadow-soft">
    <div class="flex flex-col gap-7 p-6 sm:p-9 lg:flex-row lg:items-end lg:justify-between">
        <div class="max-w-2xl"><p class="mb-3 text-sm font-bold text-white/60">حساب کاربری / مشارکت‌های من</p><h1 class="text-3xl font-extrabold tracking-tight sm:text-4xl">مشارکت‌های من</h1><p class="mt-4 max-w-xl text-base leading-8 text-white/75">اینجا می‌توانید مشارکت‌ها، تجربه‌ها و مکان‌های ذخیره‌شده‌تان را یک‌جا ببینید و هر کاری که نیاز به پیگیری دارد را سریع ادامه دهید.</p></div>
        <a class="button-primary shrink-0 bg-white text-ink hover:bg-soft" href="{{ route('contribute') }}">+ افزودن مکان یا تجربه</a>
    </div>
</div>

<section aria-labelledby="summary-title" class="mt-6"><h2 id="summary-title" class="sr-only">خلاصه مشارکت‌ها</h2><div class="grid gap-3 sm:grid-cols-3">
    <div class="rounded-2xl border border-pomegranate/20 bg-pomegranate/5 p-5"><span class="text-sm font-semibold text-secondary">نیازمند پیگیری</span><strong class="mt-2 block text-3xl font-extrabold text-pomegranate">{{ $attentionCount }}</strong><span class="mt-1 block text-sm text-muted">پیش‌نویس یا پیام تازه</span></div>
    <div class="rounded-2xl border border-border bg-surface p-5"><span class="text-sm font-semibold text-secondary">مکان‌های پیشنهادی</span><strong class="mt-2 block text-3xl font-extrabold">{{ $businesses->total() }}</strong><span class="mt-1 block text-sm text-muted">ثبت‌شده توسط شما</span></div>
    <div class="rounded-2xl border border-border bg-surface p-5"><span class="text-sm font-semibold text-secondary">تجربه‌های نوشته‌شده</span><strong class="mt-2 block text-3xl font-extrabold">{{ $reviews->total() }}</strong><span class="mt-1 block text-sm text-muted">نظر و امتیاز شما</span></div>
</div></section>

<section aria-labelledby="attention-title" class="mt-10"><div class="mb-4 flex items-end justify-between gap-4"><div><p class="text-sm font-bold text-pomegranate">اول این‌ها را ببینید</p><h2 id="attention-title" class="mt-1 text-2xl font-extrabold">کارهای نیازمند توجه</h2></div><span class="hidden text-sm text-muted sm:block">{{ $attentionCount }} مورد</span></div>
<div class="grid gap-5 lg:grid-cols-2">
<section class="panel border-pomegranate/30 bg-pomegranate/[0.03]" aria-labelledby="drafts-title"><div class="flex items-start justify-between gap-4"><div><h3 id="drafts-title" class="text-xl font-bold">پیش‌نویس‌های ناتمام</h3><p class="mt-2 text-sm leading-6 text-muted">پیش‌نویس‌ها هفت روز پس از آخرین ذخیره نگهداری می‌شوند.</p></div><span class="rounded-full bg-pomegranate/10 px-3 py-1 text-sm font-bold text-pomegranate">{{ $drafts->total() }}</span></div><div class="mt-5 divide-y divide-border">@forelse($drafts as $draft)<div class="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><p class="font-bold">{{ $draft->payload['name'] ?? 'مشارکت تازه' }}</p><div class="flex flex-wrap gap-2"><a class="button-primary" href="{{ route('contribute', ['draft' => $draft->id]) }}">ادامه / اصلاح</a><button class="button-secondary" type="button" data-discard-draft="{{ $draft->id }}">حذف پیش‌نویس</button></div></div>@empty<p class="py-4 text-muted">پیش‌نویس ذخیره‌شده ندارید.</p>@endforelse</div>{{ $drafts->links() }}</section>
<section class="panel" aria-labelledby="notifications-title"><div class="flex items-start justify-between gap-4"><div><h3 id="notifications-title" class="text-xl font-bold">پیام‌های مدیریت</h3><p class="mt-2 text-sm leading-6 text-muted">آخرین وضعیت ارسال‌ها و تجربه‌های شما.</p></div><span class="rounded-full bg-soft px-3 py-1 text-sm font-bold text-secondary">{{ $notifications->total() }}</span></div><div class="mt-5 divide-y divide-border">@forelse($notifications as $notification)<div class="py-4 first:pt-0"><p class="font-bold text-pomegranate">{{ $labels[$notification->data['status']] ?? $notification->data['status'] }}</p><p class="mt-2 leading-7 text-secondary">{{ $notification->data['reason'] }}</p></div>@empty<p class="py-4 text-muted">پیام تازه‌ای ندارید.</p>@endforelse</div>{{ $notifications->links() }}</section>
</div></section>

<div class="mt-10 grid gap-5 lg:grid-cols-2">
<section class="panel" aria-labelledby="businesses-title"><div class="mb-4 flex items-center justify-between gap-4"><h2 id="businesses-title" class="text-xl font-bold">مکان‌های پیشنهادی من</h2><span class="text-sm text-muted">{{ $businesses->total() }} مورد</span></div>@forelse($businesses as $business)<div class="border-t border-border py-4 first:border-0 first:pt-0"><h3 class="font-bold">{{ $business->name }}</h3><p class="my-2 text-sm font-semibold text-pomegranate">{{ $labels[$business->status] ?? $business->status }}</p>@if($business->moderation_reason)<p class="text-sm leading-7 text-secondary">{{ $business->moderation_reason }}</p>@endif @if($business->status === 'approved')<a class="button-secondary mt-3" href="{{ route('businesses.show', $business->slug) }}">مشاهده مکان</a>@endif</div>@empty<p class="text-muted">هنوز مکانی پیشنهاد نکرده‌اید.</p>@endforelse{{ $businesses->links() }}</section>
<section class="panel" aria-labelledby="reviews-title"><div class="mb-4 flex items-center justify-between gap-4"><h2 id="reviews-title" class="text-xl font-bold">تجربه‌های من</h2><span class="text-sm text-muted">{{ $reviews->total() }} مورد</span></div>@forelse($reviews as $review)<div class="border-t border-border py-4 first:border-0 first:pt-0"><div class="flex flex-wrap items-center justify-between gap-2"><h3 class="font-bold">{{ $review->business->name }}</h3><span class="text-sm font-semibold text-pomegranate">{{ $review->trashed() ? 'حذف‌شده' : ($labels[$review->status] ?? $review->status) }} · {{ $review->rating }} ★</span></div><p class="my-3 whitespace-pre-wrap leading-7 text-secondary">{{ $review->body }}</p><div class="mb-4 flex flex-wrap gap-3">@foreach($review->photos as $photo)<div><img class="size-20 rounded-lg object-cover" src="{{ route('media.show', [$photo, 'thumbnail' => 1]) }}" alt="عکس تجربه من"><form method="post" action="{{ route('media.destroy', $photo) }}">@csrf @method('delete')<button class="button-secondary mt-1">حذف عکس</button></form></div>@endforeach</div><div class="flex flex-wrap gap-2">@if($review->business->status === 'approved')<a class="button-secondary" href="{{ route('businesses.show', $review->business->slug) }}">مشاهده مکان</a>@endif<a class="button-secondary" href="{{ route('reviews.edit', $review->id) }}">ویرایش تجربه</a>@unless($review->trashed())<form method="post" action="{{ route('reviews.destroy', $review) }}">@csrf @method('delete')<button class="button-secondary">حذف تجربه</button></form>@endunless</div></div>@empty<p class="text-muted">هنوز تجربه‌ای ثبت نکرده‌اید.</p>@endforelse{{ $reviews->links() }}</section>
</div>

<section class="panel mt-5" aria-labelledby="saved-title"><div class="mb-4 flex items-center justify-between gap-4"><h2 id="saved-title" class="text-xl font-bold">مکان‌های ذخیره‌شده</h2><span class="text-sm text-muted">{{ $saved->total() }} مورد</span></div>@forelse($saved as $business)<a class="button-secondary m-1" href="{{ route('businesses.show', $business->slug) }}">{{ $business->name }} · {{ $business->city }}</a>@empty<p class="text-muted">هنوز مکانی ذخیره نکرده‌اید.</p>@endforelse{{ $saved->links() }}</section>
@endsection
